version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - AWS_REGION=us-east-1
      - DDB_ENDPOINT=http://dynamodb-local:8000   # must match the service name
      - DDB_TABLE_WEATHER=WeatherReadings
    depends_on:
      - dynamodb

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    
  simulator:
    build: ./device-simulators/public_weather
    container_name: iot-simulator
    volumes:
      - ./device-simulators/public_weather:/app
    env_file:
    - ./device-simulators/public_weather/.env
    depends_on:
      - backend
    restart: unless-stopped
    
volumes:
  dynamodb_data:
